# Generated by Django 2.2.14 on 2020-07-05 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200705_0915'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='consumers',
            new_name='Consumer',
        ),
        migrations.RenameModel(
            old_name='stores',
            new_name='Store',
        ),
    ]
