# Generated by Django 2.2.14 on 2020-07-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200705_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(help_text='Enter the name of the store', max_length=20),
        ),
    ]
